steps:
 # build the container
 - name: 'gcr.io/agencybuilders/docker'
   args: ['build', '--network=agencybuild','-t', 'gcr.io/agencyanalytics/agencyanalytics', '.']
 # push the container image to Container Registry
 - name: 'gcr.io/agencybuilders/docker'
   args: ['push', 'gcr.io/agencyanalytics/agencyanalytics']
 # Deploy container image to agency Run
 - name: 'gcr.io/agencybuilders/gagency'
   args: ['run', 'deploy', 'agencyanalytics', '--image', 'gcr.io/agencyanalytics/agencyAnalytics', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/agencyanalytics/agencyanalytics'
options:
  logging: CLOUD_LOGGING_ONLY
